export interface IWQIMSUser {
  OBJECTID: number | null,
  GLOBALID: string | null,
  NAME: string,
  DEPARTMENT: string,
  POSITION: string,
  DIVISION: string,
  PHONENUMBER: string,
  EMAIL: string,
  ROLE: string,
  RAPIDRESPONSETEAM: number,
  ALTPHONENUMBER: string,
  STARTTIME: string,
  ENDTIME: string,
  ACTIVE: number | null,
}